sudo: false
cache:
  directories:
  - $HOME/.m2
jdk: oraclejdk7
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-22.0.0
    - build-tools-22.0.1
    - build-tools-21.1.2
    - build-tools-21.1.1
    - android-24
    - addon-google_apis-google-24
    - android-23
    - addon-google_apis-google-23
    - android-22
    - addon-google_apis-google-22
    - android-21
    - addon-google_apis-google-21
    - android-19
    - addon-google_apis-google-19
    - android-18
    - addon-google_apis-google-18
    - android-17
    - addon-google_apis-google-17
    - android-16
    - addon-google_apis-google-16
    - android-15
    - addon-google_apis-google-15
    - android-10
    - android-8
    - extra-google-m2repository
    - extra-android-m2repository
script: mvn -B install --quiet
